import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import Script from "next/script";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Script 
          src="https://kit.fontawesome.com/ae61999827.js" 
          crossOrigin="anonymous" />
       <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
